version: '3'

services:
  server:
    build: ./server
    expose:
      - ${APP_SERVER_PORT}
    environment:
      API_HOST: ${API_HOST}
      APP_SERVER_PORT: ${APP_SERVER_PORT}
    ports:
      -  ${APP_SERVER_PORT}:${APP_SERVER_PORT}
    # volumes:
    #   - .server/auth:/usr/src/app-server/auth
    #   - .server/config:/usr/src/app-server/config
    #   - .server/model:/usr/src/app-server/model
    #   - .server/routes:/usr/src/app-server/routes
    #   - .server/server.js:/usr/src/app-server/server.js
    command: npm run dev-b

  client:
    build: ./client
    expose:
      - ${REACT_APP_PORT}
    environment:
      REACT_APP_PORT: ${REACT_APP_PORT}
    ports:
      -  ${REACT_APP_PORT}:${REACT_APP_PORT}
    # volumes:
    #   - .client/src:/usr/src/app-client/src
    #   - .client/public:/usr/src/app-client/public
    command: npm run dev-f